/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.pamo.mobile.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.pamo.mobile.controller.CustomerFormController;
import lk.pamo.mobile.modal.Customer;

/**
 *
 * @author HP
 */
public class CustomerForm extends javax.swing.JFrame {

	/**
	 * Creates new form CustomerForm
	 */
	public CustomerForm() {
		initComponents();
		getAll();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtn = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCustomerTp = new javax.swing.JTextField();
        btnSaveCustomer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRadiFemale = new javax.swing.JRadioButton();
        btnRadiMale = new javax.swing.JRadioButton();
        txtCustomerName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        btnUpdate = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Manage");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/member_48px.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(782, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, 50));

        txtCustomerEmail.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtCustomerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 240, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Customer ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 50));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 50));

        txtCustomerID.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 240, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Customer Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 50));

        txtCustomerAddress.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 240, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Contact Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 130, 50));

        txtCustomerTp.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtCustomerTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 240, 30));

        btnSaveCustomer.setBackground(new java.awt.Color(0, 255, 102));
        btnSaveCustomer.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSaveCustomer.setText("Save ");
        btnSaveCustomer.setBorder(null);
        btnSaveCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 80, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Customer Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 50));

        btnRadiFemale.setBackground(new java.awt.Color(0, 204, 204));
        genderBtn.add(btnRadiFemale);
        btnRadiFemale.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRadiFemale.setForeground(new java.awt.Color(102, 102, 102));
        btnRadiFemale.setText("Female");
        btnRadiFemale.setBorder(null);
        jPanel1.add(btnRadiFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 100, 30));

        btnRadiMale.setBackground(new java.awt.Color(0, 204, 204));
        genderBtn.add(btnRadiMale);
        btnRadiMale.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRadiMale.setForeground(new java.awt.Color(102, 102, 102));
        btnRadiMale.setText("Male");
        btnRadiMale.setBorder(null);
        jPanel1.add(btnRadiMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 110, 30));

        txtCustomerName.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 240, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/save_40px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 460, 530));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cutomer ID", "Name", "Gender", "Address", "Contact Number", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CustomerTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 410));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 80, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/search_40px.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 40, 40));

        txtSearch.setBackground(new java.awt.Color(51, 153, 255));
        txtSearch.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(null);
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 210, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 196, 11));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel14.setText("Customer Table");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 180, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 60));

        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setBackground(new java.awt.Color(0, 102, 204));
        btnUpdate.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 40));

        btnDeleteCustomer.setBackground(new java.awt.Color(255, 0, 51));
        btnDeleteCustomer.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDeleteCustomer.setText("Delete");
        btnDeleteCustomer.setBorder(null);
        btnDeleteCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnDeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/delete_bin_40px.png"))); // NOI18N
        kGradientPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 40, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/update_user_40px.png"))); // NOI18N
        kGradientPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 40));

        jPanel2.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 640, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 640, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCustomerActionPerformed
		try {
			// TODO add your handling code here:
			String id = txtCustomerID.getText();
			String name = txtCustomerName.getText();
			String address = txtCustomerAddress.getText();
			int tp = Integer.parseInt(txtCustomerTp.getText());
			String email = txtCustomerEmail.getText();
			btnRadiMale.setActionCommand("male");
			btnRadiFemale.setActionCommand("female");

			String gender = genderBtn.getSelection().getActionCommand();


			Customer c1 = new Customer(id,name,gender,address,tp,email);

			if(new CustomerFormController().saveCustomer(c1)){
				JOptionPane.showMessageDialog(this, "Saved");
				DefaultTableModel dtm = (DefaultTableModel) CustomerTable.getModel();
				Object[] rowData = {
					c1.getCustomerID(),
					c1.getCustomerName(),
					c1.getGender(),
					c1.getCustomerAddress(),
					c1.getCustomerMobileNumber(),
					c1.getCustomerEmail()
				};
				dtm.addRow(rowData);
				txtCustomerID.setText(null);
				txtCustomerName.setText(null);
				txtCustomerAddress.setText(null);
				txtCustomerTp.setText(null);
				txtCustomerEmail.setText(null);
				btnRadiFemale.setText(null);
				btnRadiMale.setText(null);
				getAll();
			}else{
				JOptionPane.showMessageDialog(this, "Try Again");
			}
		} catch (ClassNotFoundException | SQLException ex) {
			Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnSaveCustomerActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        // TODO add your handling code here:
		try {


            if(new CustomerFormController().deleteCustomer(txtCustomerID.getText())){
                JOptionPane.showMessageDialog(this, "Deleted");
				txtCustomerID.setText(null);
				txtCustomerName.setText(null);
				txtCustomerAddress.setText(null);
				txtCustomerTp.setText(null);
				txtCustomerEmail.setText(null);
				btnRadiFemale.setText(null);
				btnRadiMale.setText(null);
				getAll();
            }else{
                JOptionPane.showMessageDialog(this, "Try Again");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
			String id = txtCustomerID.getText();
            String name = txtCustomerName.getText();
            btnRadiMale.setActionCommand("male");
			btnRadiFemale.setActionCommand("female");

			String gender = genderBtn.getSelection().getActionCommand();
            String address = txtCustomerAddress.getText();
            int tp = Integer.parseInt(txtCustomerTp.getText());
            String email = txtCustomerEmail.getText();

			Customer c1 = new Customer(id,name,gender,address,tp,email);

            try {

            if(new CustomerFormController().updateCustomer(c1)){
                JOptionPane.showMessageDialog(this, "Updated");
				txtCustomerID.setText(null);
				txtCustomerName.setText(null);
				txtCustomerAddress.setText(null);
				txtCustomerTp.setText(null);
				txtCustomerEmail.setText(null);
				btnRadiFemale.setText(null);
				btnRadiMale.setText(null);
				getAll();
            }else{
                 JOptionPane.showMessageDialog(this, "Try Again");
            }


        } catch (ClassNotFoundException | SQLException ex) {
			Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
		String id = txtSearch.getText();
		String SQL = "Select * From Supplier where customer_ID=?";
		try {
			Class.forName("com.mysql.jdbc.Driver");
			Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobileshopmanagementsystem", "root", "1234");
			PreparedStatement stm = connection.prepareStatement(SQL);
			stm.setObject(1, id);
			ResultSet rst = stm.executeQuery();
			if (rst.next()) {
				txtCustomerID.setText(id);
				txtCustomerName.setText(rst.getString("customer_Name"));
				btnRadiMale.setText(rst.getString("Male"));
				btnRadiFemale.setText(rst.getString("Female"));
				txtCustomerAddress.setText(rst.getString("customer_Address"));
				txtCustomerEmail.setText(rst.getString("customer_Email"));
				txtCustomerTp.setText(rst.getString("customer_Mobile_Number"));
			} else {
				JOptionPane.showMessageDialog(this, "No Customer found..");
			}
		} catch (ClassNotFoundException ex) {
			JOptionPane.showMessageDialog(this, "Driver Not found");
		} catch (SQLException ex) {
			Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnSearchActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CustomerForm().setVisible(true);
			}
		});
	}

	private void getAll() {
		try {
			ArrayList<Customer> allcustomers = CustomerFormController.getAllCustomers();
			DefaultTableModel dtm = (DefaultTableModel) CustomerTable.getModel();
			dtm.setRowCount(0);
			for (Customer customer : allcustomers) {
				Object[] rowData = {customer.getCustomerID(), customer.getCustomerName(), customer.getGender(), customer.getCustomerAddress(), customer.getCustomerMobileNumber(), customer.getCustomerEmail()};
				dtm.addRow(rowData);
			}
		} catch (ClassNotFoundException | SQLException ex) {
			Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CustomerTable;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JRadioButton btnRadiFemale;
    private javax.swing.JRadioButton btnRadiMale;
    private javax.swing.JButton btnSaveCustomer;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup genderBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerTp;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
