/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.pamo.mobile.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.pamo.mobile.controller.SupplierFormController;
import lk.pamo.mobile.modal.Supplier;

/**
 *
 * @author HP
 */
public class SupplierForm extends javax.swing.JFrame {

	/**
	 * Creates new form SupplierForm
	 */
	public SupplierForm() {
		initComponents();
		getAll();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSupplierTp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSupplierID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSupplierAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSupplierEmail = new javax.swing.JTextField();
        btnSaveSupplier = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSupplierNIC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDateTime = new javax.swing.JTextField();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel10 = new javax.swing.JLabel();
        btnUpdateSupplier = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnDeleteSupplier = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SupplierTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 130, 50));

        txtSupplierTp.setBackground(new java.awt.Color(204, 255, 255));
        txtSupplierTp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierTpActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupplierTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 240, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Supplier ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 50));

        txtSupplierID.setBackground(new java.awt.Color(204, 255, 255));
        txtSupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 240, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Supplier Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 50));

        txtSupplierAddress.setBackground(new java.awt.Color(204, 255, 255));
        txtSupplierAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupplierAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 240, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Contact Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, 50));

        txtSupplierEmail.setBackground(new java.awt.Color(204, 255, 255));
        txtSupplierEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupplierEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 240, 30));

        btnSaveSupplier.setBackground(new java.awt.Color(0, 255, 102));
        btnSaveSupplier.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSaveSupplier.setText("Save ");
        btnSaveSupplier.setBorder(null);
        btnSaveSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 80, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Supplier NIC");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 50));

        txtSupplierNIC.setBackground(new java.awt.Color(204, 255, 255));
        txtSupplierNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNICActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupplierNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 240, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/save_40px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 50, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Supplier Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 50));

        txtSupplierName.setBackground(new java.awt.Color(204, 255, 255));
        txtSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 460, 520));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supplier Manage");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/supplier_48px.png"))); // NOI18N

        txtDateTime.setEditable(false);
        txtDateTime.setBackground(new java.awt.Color(204, 204, 255));
        txtDateTime.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        txtDateTime.setForeground(new java.awt.Color(0, 102, 102));
        txtDateTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 669, Short.MAX_VALUE)
                .addComponent(txtDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDateTime)
                .addContainerGap())
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 60));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/update_user_40px.png"))); // NOI18N

        btnUpdateSupplier.setBackground(new java.awt.Color(0, 102, 204));
        btnUpdateSupplier.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnUpdateSupplier.setText("Update");
        btnUpdateSupplier.setBorder(null);
        btnUpdateSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSupplierActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/delete_bin_40px.png"))); // NOI18N

        btnDeleteSupplier.setBackground(new java.awt.Color(255, 0, 51));
        btnDeleteSupplier.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDeleteSupplier.setText("Delete");
        btnDeleteSupplier.setBorder(null);
        btnDeleteSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addGap(20, 20, 20)
                .addComponent(btnUpdateSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel14)
                .addGap(20, 20, 20)
                .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(btnUpdateSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 680, 60));

        jPanel2.setBackground(new java.awt.Color(204, 102, 255));

        SupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Name", "NIC", "Address", "Email", "Contact Nubmer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        SupplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SupplierTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 680, 400));

        jPanel3.setBackground(new java.awt.Color(204, 102, 255));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/pamo/mobile/Images/search_40px.png"))); // NOI18N

        txtSearch.setBackground(new java.awt.Color(204, 102, 255));
        txtSearch.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Supplier Table");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 680, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSupplierActionPerformed

		// TODO add your handling code here:
		String id = txtSupplierID.getText();
		String name = txtSupplierName.getText();
		String nic = txtSupplierNIC.getText();
		String address = txtSupplierAddress.getText();
		String email = txtSupplierEmail.getText();
		int tp = Integer.parseInt(txtSupplierTp.getText());

		Supplier s1 = new Supplier(id, name, nic, address, email, tp);

		try {

			if (new SupplierFormController().saveSupplier(s1)) {
				JOptionPane.showMessageDialog(this, "Saved");
				DefaultTableModel dtm = (DefaultTableModel) SupplierTable.getModel();
				Object[] rowData = {
					s1.getSupplier_id(),
					s1.getSupplier_Name(),
					s1.getSupplier_NIC(),
					s1.getSupplier_Address(),
					s1.getSupplier_Email(),
					s1.getSupplier_Mobile_Number()
				};
				dtm.addRow(rowData);
				txtSupplierID.setText(null);
				txtSupplierName.setText(null);
				txtSupplierNIC.setText(null);
				txtSupplierAddress.setText(null);
				txtSupplierEmail.setText(null);
				txtSupplierTp.setText(null);
				getAll();
			} else {
				JOptionPane.showMessageDialog(this, "Try Again");
			}

		} catch (ClassNotFoundException | SQLException ex) {
			Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
		}

    }//GEN-LAST:event_btnSaveSupplierActionPerformed

    private void btnDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplierActionPerformed
		// TODO add your handling code here:
		try {

			if (new SupplierFormController().deleteSupplier(txtSupplierID.getText())) {
				JOptionPane.showMessageDialog(this, "Deleted");
				txtSupplierID.setText(null);
				txtSupplierName.setText(null);
				txtSupplierNIC.setText(null);
				txtSupplierAddress.setText(null);
				txtSupplierEmail.setText(null);
				txtSupplierTp.setText(null);
				getAll();
			} else {
				JOptionPane.showMessageDialog(this, "Try Again");
			}

		} catch (ClassNotFoundException | SQLException ex) {
			Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnDeleteSupplierActionPerformed

    private void btnUpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSupplierActionPerformed
		// TODO add your handling code here:
		String id = txtSupplierID.getText();
		String name = txtSupplierName.getText();
		String nic = txtSupplierNIC.getText();
		String address = txtSupplierAddress.getText();
		String email = txtSupplierEmail.getText();
		int tp = Integer.parseInt(txtSupplierTp.getText());

		Supplier s1 = new Supplier(id, name, nic, address, email, tp);

		try {

			if (new SupplierFormController().updateSupplier(s1)) {
				JOptionPane.showMessageDialog(this, "Updated");

				txtSupplierID.setText(null);
				txtSupplierName.setText(null);
				txtSupplierNIC.setText(null);
				txtSupplierAddress.setText(null);
				txtSupplierEmail.setText(null);
				txtSupplierTp.setText(null);
				getAll();
			} else {
				JOptionPane.showMessageDialog(this, "Try Again");
			}

		} catch (ClassNotFoundException | SQLException ex) {
			Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnUpdateSupplierActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
		// TODO add your handling code here:
		String id = txtSearch.getText();
		String SQL = "Select * From Supplier where supplier_ID=?";
		try {
			Class.forName("com.mysql.jdbc.Driver");
			Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mobileshopmanagementsystem", "root", "1234");
			PreparedStatement stm = connection.prepareStatement(SQL);
			stm.setObject(1, id);
			ResultSet rst = stm.executeQuery();
			if (rst.next()) {
				txtSupplierID.setText(id);
				txtSupplierName.setText(rst.getString("supplier_Name"));
				txtSupplierNIC.setText(rst.getString("supplier_NIC"));
				txtSupplierAddress.setText(rst.getString("supplier_Address"));
				txtSupplierEmail.setText(rst.getString("supplier_Email"));
				txtSupplierTp.setText(rst.getString("supplier_Mobile_Number"));
			} else {
				JOptionPane.showMessageDialog(this, "No Supplier found..");
			}
		} catch (ClassNotFoundException ex) {
			JOptionPane.showMessageDialog(this, "Driver Not found");
		} catch (SQLException ex) {
			Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtDateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateTimeActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtDateTimeActionPerformed

    private void txtSupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierIDActionPerformed
		// TODO add your handling code here:
		txtSupplierID.requestFocus();
    }//GEN-LAST:event_txtSupplierIDActionPerformed

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
		// TODO add your handling code here:
		txtSupplierName.requestFocus();
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void txtSupplierNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNICActionPerformed
		// TODO add your handling code here:
		txtSupplierNIC.requestFocus();
    }//GEN-LAST:event_txtSupplierNICActionPerformed

    private void txtSupplierAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierAddressActionPerformed
		// TODO add your handling code here:
		txtSupplierAddress.requestFocus();
    }//GEN-LAST:event_txtSupplierAddressActionPerformed

    private void txtSupplierEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierEmailActionPerformed
		// TODO add your handling code here:
		txtSupplierEmail.requestFocus();
    }//GEN-LAST:event_txtSupplierEmailActionPerformed

    private void txtSupplierTpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierTpActionPerformed
		// TODO add your handling code here:
		txtSupplierTp.requestFocus();
    }//GEN-LAST:event_txtSupplierTpActionPerformed

    private void SupplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierTableMouseClicked
		int selectedRow=SupplierTable.getSelectedRow();
		txtSupplierID.setText( SupplierTable.getValueAt(selectedRow, 0).toString());
		txtSupplierName.setText( SupplierTable.getValueAt(selectedRow, 1).toString());
		txtSupplierNIC.setText( SupplierTable.getValueAt(selectedRow, 2).toString());
		txtSupplierAddress.setText( SupplierTable.getValueAt(selectedRow, 3).toString());
		txtSupplierEmail.setText( SupplierTable.getValueAt(selectedRow, 4).toString());
		txtSupplierTp.setText( SupplierTable.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_SupplierTableMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SupplierForm().setVisible(true);
			}
		});
	}

	private void getAll() {
		try {
			ArrayList<Supplier> allsuppliers = SupplierFormController.getAllSuppliers();
			DefaultTableModel dtm = (DefaultTableModel) SupplierTable.getModel();
			dtm.setRowCount(0);
			for (Supplier supplier : allsuppliers) {
				Object[] rowData = {supplier.getSupplier_id(), supplier.getSupplier_Name(), supplier.getSupplier_NIC(), supplier.getSupplier_Address(), supplier.getSupplier_Email(), supplier.getSupplier_Mobile_Number()};
				dtm.addRow(rowData);
			}
		} catch (ClassNotFoundException | SQLException ex) {
			Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
		}
	}






    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SupplierTable;
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnSaveSupplier;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField txtDateTime;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextField txtSupplierEmail;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtSupplierNIC;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierTp;
    // End of variables declaration//GEN-END:variables
}
